schema:
  format:
    openapi: "3.0.0"
  environment_input_type: "PublicEnvironmentInput"
  types:
    PublicEnvironmentInput:
      type: object
      description: "Input properties for my environment"
      properties:
        region:
          type: string
          description: "The region to provision "
          default: "eu-west-1"
        vpc_cidr:
          type: string
          description: "CIDR IP of the VPC"
          pattern: ([0-9]{1,3}\.){3}[0-9]{1,3}($|/(16|24))
        master_subnet_cidr1:
          type: string
          description: "CIDR IP of the master_subnet from availability zone 1"
          default: "10.42.0.0/20"  
        master_subnet_cidr2:
          type: string
          description: "CIDR IP of the master_subnet from availability zone 2"
          default: "10.42.16.0/20"  
        master_subnet_cidr3:
          type: string
          description: "CIDR IP of the master_subnet from availability zone 3"
          default: "10.42.32.0/20"
        worker_subnet_cidr1:
          type: string
          description: "CIDR IP of the worker_subnet from availability zone 1"
          default: "10.42.128.0/20"
        worker_subnet_cidr2:
          type: string
          description: "CIDR IP of the worker_subnet from availability zone 2"
          default: "10.42.144.0/20"
        worker_subnet_cidr3:
          type: string
          description: "CIDR IP of the worker_subnet from availability zone 3"
          default: "10.42.160.0/20"
   


